server:
  port: 9090
spring:
  servlet:
    multipart:
      max-file-size: 10MB # 单个文件大小
      max-request-size: 100MB # 设置总上传的数据大小
      enabled: true #开启
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
    url: jdbc:mysql://localhost:3306/activity?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: activity
    password: 2222
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
